Add db-sync checks for conway param update proposals [ CIP-080 -> CIP 083 ]
IntersectMBO/cardano-node-tests pull request #2414
Opened 2024-05-08 20:44 UTC by ArturWieczorek

Add db-sync checks for conway param update proposals [ CIP-080 -> CIP 083 ]

2024-05-08 20:48 UTC, ArturWieczorek commented
Existing tests in file are passing (ran several times):

```sh
[nix-shell:~/Downloads/CIPsTests/cardano-node-tests](artur/cip-tests)$ pytest -sk "test_pparam_update" cardano_node_tests/
=============================================================================================================================================== test session starts ================================================================================================================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /nix/store/lx8vhp4fxclp494svlfis3sb2g8z4l9h-python3-3.10.12/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/artur/Downloads/CIPsTests/cardano-node-tests/.hypothesis/examples'))
metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.15.0-106-generic-x86_64-with-glibc2.37', 'Packages': {'pytest': '7.4.4', 'pluggy': '1.5.0'}, 'Plugins': {'allure-pytest': '2.13.5', 'hypothesis': '6.100.2', 'html': '3.2.0', 'metadata': '3.1.1', 'order': '1.2.1', 'select': '0.1.2', 'xdist': '3.3.1'}, 'cardano-node': '8.10.0', 'cardano-node rev': '04e060e6d86a5791c00aa518b2cee025384be28b', 'cardano-node ghc': 'ghc-8.10', 'cardano-cli': '8.22.0.0', 'cardano-cli rev': '04e060e6d86a5791c00aa518b2cee025384be28b', 'cardano-cli ghc': 'ghc-8.10', 'CLUSTER_ERA': 'conway', 'TX_ERA': '', 'COMMAND_ERA': 'conway', 'SCRIPTS_DIRNAME': 'conway_fast', 'ENABLE_P2P': 'False', 'MIXED_P2P': 'False', 'NUM_POOLS': '3', 'DB_BACKEND': '', 'HAS_CC': 'True', 'cardano-node-tests rev': 'ad6b634c9e05db763c3705e1805ab8b0c10bc390', 'cardano-node-tests url': 'https://github.com/IntersectMBO/cardano-node-tests/tree/ad6b634c9e05db763c3705e1805ab8b0c10bc390', 'CARDANO_NODE_SOCKET_PATH': '/home/artur/Downloads/CIPsTests/cardano-node-tests/dev_workdir/state-cluster0/bft1.socket', 'cardano-cli exe': '/nix/store/r716z228al13457i2k2wlgflr9l0ldpg-cardano-cli-exe-cardano-cli-8.22.0.0/bin/cardano-cli', 'cardano-node exe': '/nix/store/yi869ay2900bv7bwq3qz6hsz0rlnhnw7-cardano-node-exe-cardano-node-8.10.0/bin/cardano-node', 'cardano-submit-api exe': '/nix/store/cx62sjxfw8n8y09x6w56xq1171f9llpl-cardano-submit-api-exe-cardano-submit-api-8.10.0/bin/cardano-submit-api', 'network magic': 42, 'HAS_DBSYNC': 'True', 'db-sync': '13.2.0.1', 'db-sync rev': '3ac426d9f7cf252d5a20a02c60d4988a43dbb3f2', 'db-sync ghc': 'ghc-8.10', 'db-sync exe': '/nix/store/5p7spghmzkfamjgidjsli8kr9fjqhix9-cardano-db-sync-exe-cardano-db-sync-13.2.0.1/bin/cardano-db-sync'}
rootdir: /home/artur/Downloads/CIPsTests/cardano-node-tests
configfile: pyproject.toml
plugins: allure-pytest-2.13.5, hypothesis-6.100.2, html-3.2.0, metadata-3.1.1, order-1.2.1, select-0.1.2, xdist-3.3.1
collected 1354 items / 1352 deselected / 2 selected                                                                                                                                                                                                                                                                

cardano_node_tests/tests/tests_conway/test_pparam_update.py::TestPParamUpdate::test_pparam_update@long 
-------------------------------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------------------------------
INFO     cardano_node_tests.tests.conftest:conftest.py:188 Changed CWD to '/home/artur/Downloads/CIPsTests/cardano-node-tests/dev_workdir/tmp/pytest-of-artur/pytest-13'.
-------------------------------------------------------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------------------------------------------------------
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 38.20 sec for slot no 91005.
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 50.20 sec for slot no 92025.
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 188.40 sec for slot no 93025.
PASSED
cardano_node_tests/tests/tests_conway/test_pparam_update.py::TestPParamData::test_pparam_keys PASSED
------------------------------------------------------------------------------------------------------------------------------------------------ live log teardown -------------------------------------------------------------------------------------------------------------------------------------------------
INFO     cardano_node_tests.utils.dbsync_conn:dbsync_conn.py:34 Closing connection to db-sync database dbsync0.


================================================================================================================================== 2 passed, 1352 deselected in 542.59s (0:09:02) ==================================================================================================================================
```


Clear errors reporting at the end of tests so CLI checks flow is not "broken" by sudden `cardano-db-sync` error.
Example:

```
        if db_errors_final:
>           raise AssertionError("\n".join(db_errors_final))
E           AssertionError: db-sync economic params update error: Unexpected parameter proposal values in db-sync:
E           Param value for monetary_expand_rate: 0.006872744448298511. Expected: {'denominator': 541996, 'numerator': 3725}
E           Param value for treasury_growth_rate: 0.05732894663164954. Expected: {'denominator': 732213, 'numerator': 41977}
E           db-sync technical params update error: Unexpected parameter proposal values in db-sync:
E           Param value for influence: 0.264608619636279. Expected: {'denominator': 721817, 'numerator': 190999}
E           db-sync governance params update error: Unexpected parameter proposal values in db-sync:
E           Param value for dvt_committee_no_confidence: 0.5411525645851631. Expected: {'denominator': 286908, 'numerator': 155261}
E           Param value for dvt_committee_normal: 0.5790609208012232. Expected: {'denominator': 518657, 'numerator': 300334}
E           Param value for dvt_hard_fork_initiation: 0.5843206610356061. Expected: {'denominator': 898469, 'numerator': 524994}
E           Param value for dvt_motion_no_confidence: 0.5374174177988559. Expected: {'denominator': 629827, 'numerator': 338480}
E           Param value for dvt_p_p_economic_group: 0.5248617199199834. Expected: {'denominator': 731848, 'numerator': 384119}
E           Param value for dvt_p_p_gov_group: 0.5777403429012142. Expected: {'denominator': 985415, 'numerator': 569314}
E           Param value for dvt_p_p_network_group: 0.5274488202473854. Expected: {'denominator': 478363, 'numerator': 252312}
E           Param value for dvt_p_p_technical_group: 0.58329398083453. Expected: {'denominator': 311289, 'numerator': 181573}
E           Param value for dvt_treasury_withdrawal: 0.553689123663014. Expected: {'denominator': 991970, 'numerator': 549243}
E           Param value for dvt_update_to_constitution: 0.5487540958052761. Expected: {'denominator': 936629, 'numerator': 513979}
E           Param value for pvt_committee_no_confidence: 0.5264449577269275. Expected: {'denominator': 962433, 'numerator': 506668}
E           Param value for pvt_committee_normal: 0.5944026539280277. Expected: {'denominator': 494663, 'numerator': 294029}
E           Param value for pvt_hard_fork_initiation: 0.5644790716053705. Expected: {'denominator': 776911, 'numerator': 438550}
E           Param value for pvt_motion_no_confidence: 0.5660339485002784. Expected: {'denominator': 991384, 'numerator': 561157}
E           Param value for pvtpp_security_group: 0.5988896134853604. Expected: {'denominator': 627169, 'numerator': 375605}
E           db-sync mixed group params update error: Unexpected para [...]

2024-05-09 19:56 UTC, ArturWieczorek commented
Tests for `Conway` Era passed :green_circle:  (with exception of CC ones - which is expected at this moment).
[testrun-report.html.tar.gz](https://github.com/IntersectMBO/cardano-node-tests/files/15267031/testrun-report.html.tar.gz)

2024-05-28 10:43 UTC, mkoura requested changes

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +) -> tp.Optional[dbsync_queries.EpochParamDBRow]:
For functions called directly from tests, we need to check that we have db-sync available.

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +) -> tp.Optional[dbsync_queries.GovActionProposalDBRow]:
For functions called directly from tests, we need to check that we have db-sync available.

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +    ledger_gov_params_proposal_json = json.dumps(update_proposal, sort_keys=True)
Why is this necessary? You can compare unsorted dicts:
```python
In [1]: {"a": 1, "b": 2} == {"b": 2, "a": 1}
Out[1]: True
```

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +    db_gov_action_description = db_gov_action.description
Why assigning to variable instead of using `db_gov_action.description`?

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +) -> tp.Optional[dbsync_queries.ParamProposalDBRow]:
For functions called directly from tests, we need to check that we have db-sync available.

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +    for param_db, protocol_value in params_map.items():
Maybe `param_name` or `param_from_db` would be better. The `param_db` is bit confusing, I was expecting the data to be some kind of dict (or other kind of database) and was surprised to see it used in `getattr` below.

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/utils/dbsync_utils.py
> +def _evaluate_pparam(pparam: tp.Any) -> tp.Union[float, None]:
Maybe something like `_get_float_pparam`?
Use `tp.Optional[float]`

2024-05-28 10:43 UTC, mkoura commented on cardano_node_tests/tests/tests_conway/test_pparam_update.py
> +            str_exc = str(exc)
This is not needed, you can use directly `f"{exc}"`

2024-07-02 11:32 UTC, mkoura requested changes

2024-07-02 11:32 UTC, mkoura commented on cardano_node_tests/tests/tests_conway/test_pparam_update.py
> +            db_errors_final.append(f"db-sync economic params update error: {str_exc}")
Can be just
```
db_errors_final.append(f"db-sync economic params update error: {exc}")
```

2024-07-02 20:13 UTC, ArturWieczorek commented
Tests passed:

```
[nix-shell:~/Downloads/Treasury_Withdrawals/cardano-node-tests](artur/cip-tests)$ pytest -sk "test_pparam_update" cardano_node_tests/
======================================================================================================================= test session starts =======================================================================================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.5.0 -- /nix/store/lx8vhp4fxclp494svlfis3sb2g8z4l9h-python3-3.10.12/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/artur/Downloads/Treasury_Withdrawals/cardano-node-tests/.hypothesis/examples'))
metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.15.0-113-generic-x86_64-with-glibc2.37', 'Packages': {'pytest': '7.4.4', 'pluggy': '1.5.0'}, 'Plugins': {'allure-pytest': '2.13.5', 'hypothesis': '6.100.2', 'html': '3.2.0', 'metadata': '3.1.1', 'order': '1.2.1', 'select': '0.1.2', 'xdist': '3.3.1'}, 'cardano-node': '8.12.1', 'cardano-node rev': '06943b66e634fc9eb83ddb376ed3508003dbb607', 'cardano-node ghc': 'ghc-8.10', 'cardano-cli': '8.24.0.0', 'cardano-cli rev': '06943b66e634fc9eb83ddb376ed3508003dbb607', 'cardano-cli ghc': 'ghc-8.10', 'CLUSTER_ERA': 'conway', 'TX_ERA': '', 'COMMAND_ERA': 'conway', 'SCRIPTS_DIRNAME': 'conway_fast', 'ENABLE_P2P': 'False', 'MIXED_P2P': 'False', 'NUM_POOLS': '3', 'DB_BACKEND': '', 'HAS_CC': 'True', 'cardano-node-tests rev': '36e7b5d18ae4094bdd788aa07799771333416498', 'cardano-node-tests url': 'https://github.com/IntersectMBO/cardano-node-tests/tree/36e7b5d18ae4094bdd788aa07799771333416498', 'CARDANO_NODE_SOCKET_PATH': '/home/artur/Downloads/Treasury_Withdrawals/cardano-node-tests/dev_workdir/state-cluster0/bft1.socket', 'cardano-cli exe': '/nix/store/52kb3arhansrzggmp2gqxf6h92dfbm04-cardano-cli-exe-cardano-cli-8.24.0.0/bin/cardano-cli', 'cardano-node exe': '/nix/store/2wjw5197lryp4lpymd4zygvlxs4f967x-cardano-node-exe-cardano-node-8.12.1/bin/cardano-node', 'cardano-submit-api exe': '/nix/store/ix9066vs9bia5nvwqf22qa12f1lzqnsp-cardano-submit-api-exe-cardano-submit-api-8.12.0/bin/cardano-submit-api', 'network magic': 42, 'HAS_DBSYNC': 'True', 'db-sync': '13.2.0.1', 'db-sync rev': 'cd10a2bf3849da5eb605ca0e92056990fb92b61d', 'db-sync ghc': 'ghc-8.10', 'db-sync exe': '/nix/store/lv0z3q20mfaldqq70wp51ipr8yasggcp-cardano-db-sync-exe-cardano-db-sync-13.2.0.1/bin/cardano-db-sync'}
rootdir: /home/artur/Downloads/Treasury_Withdrawals/cardano-node-tests
configfile: pyproject.toml
plugins: allure-pytest-2.13.5, hypothesis-6.100.2, html-3.2.0, metadata-3.1.1, order-1.2.1, select-0.1.2, xdist-3.3.1
collected 1421 items / 1419 deselected / 2 selected                                                                                                                                                                                                               

cardano_node_tests/tests/tests_conway/test_pparam_update.py::TestPParamUpdate::test_pparam_update@long 
------------------------------------------------------------------------------------------------------------------------- live log setup --------------------------------------------------------------------------------------------------------------------------
INFO     cardano_node_tests.tests.conftest:conftest.py:188 Changed CWD to '/home/artur/Downloads/Treasury_Withdrawals/cardano-node-tests/dev_workdir/tmp/pytest-of-artur/pytest-0'.
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 58.00 sec for slot no 1025.
-------------------------------------------------------------------------------------------------------------------------- live log call --------------------------------------------------------------------------------------------------------------------------
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 40.40 sec for slot no 2005.
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 126.20 sec for slot no 3025.
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:372 Waiting for 194.60 sec for slot no 4025.
PASSED
cardano_node_tests/tests/tests_conway/test_pparam_update.py::TestPParamData::test_pparam_keys PASSED
------------------------------------------------------------------------------------------------------------------------ live log teardown ------------------------------------------------------------------------------------------------------------------------
INFO     cardano_node_tests.utils.dbsync_conn:dbsync_conn.py:34 Closing connection to db-sync database dbsync0.


========================================================================================================= 2 passed, 1419 deselected in 691.20s (0:11:31) ==========================================================================================================
```

2024-07-04 17:58 UTC, mkoura approved these changes

2024-07-09 11:07 UTC, merged