Add governance guardrails tests for update pparams
IntersectMBO/cardano-node-tests pull request #2501
Opened 2024-07-29 19:00 UTC by nabinpkl

This PR proposes tests for governance guardrails. This is based on the Plutus Governance guardrails script and default constitution. At first, the script is enacted and then checked for unconstitutional values/out-of-range values for all protocol parameters defined in the constitution along with a check to ensure that valid values are accepted as a protocol parameter governance action.

The parameters and their values are checked based on Plutus cardano-constitution.

commit [db119872c0dfc8537a39d38cea8ef0b20c59ecb5](https://github.com/IntersectMBO/plutus/tree/db119872c0dfc8537a39d38cea8ef0b20c59ecb5/cardano-constitution)

The default constitution file
https://github.com/IntersectMBO/plutus/blob/db119872c0dfc8537a39d38cea8ef0b20c59ecb5/cardano-constitution/data/defaultConstitution.json

The user stories are derived from this PR.
https://github.com/IntersectMBO/cardano-test-plans/pull/52

2024-08-01 18:02 UTC, mkoura requested changes
Thanks for the PR. So far I took only brief look and have several comments.

There can be improvements made to enable parallel run of the tests (they don't change the environment, apart from the setup, so I believe they can run in parallel) and collateral handling.

If you don't mind, I'll do the changes, it will be faster for me than writing detailed comments.

2024-08-02 19:41 UTC, nabinpkl commented on cardano_node_tests/tests/common.py
> +def create_collaterals(
Thank you for the feedback. This has been moved to clustelib_utils with the slicing of utxos on the latest update.

2024-08-02 19:41 UTC, nabinpkl commented on cardano_node_tests/tests/common.py
> +    ]
This has been moved to clustelib_utils with the slicing of utxos on the latest update.

2024-08-02 19:41 UTC, nabinpkl commented on cardano_node_tests/tests/tests_conway/test_guardrails.py
> +class ClusterWithConstitutionRecord:
Right. This has been updated to simpler dataclass.

2024-08-02 19:41 UTC, nabinpkl commented on cardano_node_tests/tests/tests_conway/test_guardrails.py
> +        constitution_action = cluster.g_conway_governance.action.create_constitution(
`propose_change_constitution` has been updated with additional optional `constitution_script_hash` parameter.

2024-08-02 19:41 UTC, nabinpkl commented on cardano_node_tests/tests/tests_conway/test_guardrails.py
> +    # Create collateral utxo for plutus script
The collateral creation step has been moved to set up.

2024-08-02 19:41 UTC, nabinpkl commented on cardano_node_tests/tests/tests_conway/test_guardrails.py
> +    dependent_proposals: List[clusterlib_utils.UpdateProposal] | Tuple,
Right. It has been updated to use Union instead.

2024-08-02 19:42 UTC, nabinpkl commented on cardano_node_tests/tests/tests_conway/test_guardrails.py
> +    cluster_manager.set_needs_respin()
I am not familiar much with the framework you mentioned. This step has been removed and I believe it needs to be updated in the CI/CD pipeline for running guardrails test.

2024-08-02 19:42 UTC, nabinpkl commented on cardano_node_tests/tests/tests_conway/test_guardrails.py
> +        propose_param_changes(cluster_with_constitution, proposals)
All the function calls with more than one argument are updated to use kwargs.

2024-08-02 19:46 UTC, nabinpkl commented
> Thanks for the PR. So far I took only brief look and have several comments.
> 
> There can be improvements made to enable parallel run of the tests (they don't change the environment, apart from the setup, so I believe they can run in parallel) and collateral handling.
> 
> If you don't mind, I'll do the changes, it will be faster for me than writing detailed comments.

Thank you for the review comments and feedback.
I have addressed some of the comments.

We'd welcome the changes you'd like to make to the PR.

It'd be great if you could push the changes directly on the PR, get it merged if possible, or merge PR and then make the necessary changes to run them in parallel. 

Or I can address those changes If there are some examples of tests currently running in parallel and how the setup is being done.

2024-08-05 17:54 UTC, mkoura commented
Looks like I cannot push to your PR. Can you give me access?

2024-08-05 18:56 UTC, nabinpkl commented
> Looks like I cannot push to your PR. Can you give me access?

I just sent you an invite. It should give access now.

2024-08-06 11:17 UTC, mkoura approved these changes

2024-08-06 11:18 UTC, merged